import { EventDispatcher, Vector3, Vector2, Matrix4 } from "three";
import { Quaternion, Euler } from "three";
import {
  EVENT_UPDATED,
  EVENT_PARAMETRIC_GEOMETRY_UPATED,
  EVENT_MOVED,
  EVENT_DELETED,
} from "../core/events";
import { Utils } from "../core/utils";
import {
  BASE_PARAMETRIC_TYPES,
  ParametricFactory,
} from "../parametrics/ParametricFactory";
import { MODEL_TYPES } from "@pazl/entities/Model";

export const UP_VECTOR = new Vector3(0, 1, 0);
/**
 * An Item is an abstract entity for all things placed in the scene, e.g. at
 * walls or on the floor.
 */
export class Item extends EventDispatcher {
  /**
   * Constructs an item. This is a pure data representation of a room item.
   * Because floorplanner is pure MVC or MVP it is the responsibility of the respective viewer
   * to create the physical entity based on the item data
   *
   * @param model
   *            TODO
   * @param metadata
   *            TODO
   * @param id
   *            TODO
   */
  constructor(metadata, model, id) {
    super();

    /**
     * @property {String} id The id of this corner. Autogenerated the first time
     * @type {String}
     **/
    this.__id = id || Utils.guide();
    this.__metadata = metadata;
    this.__model = model;
    this.__position2d = new Vector2();
    this.__position = new Vector3();
    this.__rotation = new Vector3();
    this.__innerRotation = new Vector3();

    /**
     * The below property should be used when setting the rotation of a physicalitem
     * Also this property is only for rendering the scene and will not be a part of the metadata
     */
    this.__combinedRotation = new Vector3();

    this.__scale = new Vector3(1, 1, 1);

    this.__size = new Vector3(1, 1, 1);
    this.__mesh = [];
    this.__meshmap = [];
    this.__halfSize = new Vector3(1, 1, 1);

    this.__customIntersectionPlanes = [];

    /** */
    this.__hover = false; //This is part of application logic only
    /** */
    this.__selected = false; //This is part of application logic only
    this.__freePosition = true; //This is part of application logic only
    this.__boundToFloor = false; //This is part of application logic only
    this.__allowRotate = true; //This is part of application logic only

    this.__fixed = false; //This is part of application logic and also Metadata
    this.__resizable = false; //This is part of application logic and also Metadata

    this.__frontVisible = false;
    this.__backVisible = false;
    this.__visible = true;
    /**
     * Set to false if you don't want animated property movements in the scene3d
     */
    this.__offlineUpdate = true;

    this.__isParametric = false;
    this.__baseParametricType = BASE_PARAMETRIC_TYPES.DOOR;
    this.__subParametricType = 1;
    this.__parametricClass = null;

    this.__currentWall = null;
    this.__currentFloor = null;
    this.__currentWallNormal = null;
    this.__currentWallSnapPoint = null;
    this.__isWallDependent = false;

    this.__followWallEvent = this.__followWall.bind(this);
    this.__edgeDeletedEvent = this.__edgeDeleted.bind(this);
    this.__parametricGeometryUpdateEvent =
      this.__parametricGeometryUpdate.bind(this);

    this.castShadow = false;
    this.receiveShadow = false;
    this.__initializeMetaData();
  }

  __initializeMetaData() {
    this.__fixed = this.__metadata.fixed ? this.__metadata.fixed : true;
    this.__resizable = this.__metadata.resizable
      ? this.__metadata.resizable
      : true;
    this.__mesh = this.__metadata.mesh ? this.__metadata.mesh : [];
    this.__meshmap = this.__metadata.meshmap ? this.__metadata.meshmap : [];

    if (this.__metadata.position.length) {
      this.__position = new Vector3()
        .fromArray(this.__metadata.position)
        .clone();
    }
    if (this.__metadata.rotation.length) {
      this.__rotation = new Vector3()
        .fromArray(this.__metadata.rotation)
        .clone();
    }
    if (this.__metadata.innerRotation) {
      this.__innerRotation = new Vector3()
        .fromArray(this.__metadata.innerRotation)
        .clone();
    } else {
      this.__innerRotation = new Vector3();
    }
    if (this.__metadata.scale.length) {
      this.__scale = new Vector3().fromArray(this.__metadata.scale).clone();
    }
    if (this.__metadata.size.length) {
      this.__size = new Vector3().fromArray(this.__metadata.size).clone();
      this.__halfSize = this.__size.clone().multiplyScalar(0.5);
    }

    if (this.__metadata.isParametric) {
      this.__isParametric = this.__metadata.isParametric;
      switch (this.__metadata.baseParametricType) {
        case BASE_PARAMETRIC_TYPES.DOOR.description:
          this.__baseParametricType = BASE_PARAMETRIC_TYPES.DOOR;
          break;
        case BASE_PARAMETRIC_TYPES.WINDOW.description:
          this.__baseParametricType = BASE_PARAMETRIC_TYPES.WINDOW;
          break;
        case BASE_PARAMETRIC_TYPES.CABINET.description:
          this.__baseParametricType = BASE_PARAMETRIC_TYPES.CABINET;
          break;
        case BASE_PARAMETRIC_TYPES.SHELVES.description:
          this.__baseParametricType = BASE_PARAMETRIC_TYPES.SHELVES;
          break;
      }
      this.__subParametricData = this.__metadata.subParametricData;
      let parametricClass = ParametricFactory.getParametricClass(
        this.__baseParametricType.description
      );
      this.__parametricClass = new (parametricClass.getClass(
        this.__subParametricData.type
      ))(this.__subParametricData);
      this.__parametricClass.addEventListener(
        EVENT_PARAMETRIC_GEOMETRY_UPATED,
        this.__parametricGeometryUpdateEvent
      );
    } else {
      this.__isParametric = false;
    }

    console.debug(
      "item.js -> __initializeMetaData -> this.__metadata",
      this.id,
      this.__model.floorplan.walls
    );
    if (this.__metadata.wall) {
      let walls = this.__model.floorplan.walls;
      for (let i = 0; i < walls.length; i++) {
        let wall = walls[i];
        if (wall.id === this.__metadata.wall) {
          let wallEdge =
            this.__metadata.wallSide === "front"
              ? wall.frontEdge
              : wall.backEdge;
          let wallSurfacePoint = this.__metadata.wallSurfacePoint;

          this.__currentWallSnapPoint = new Vector3(
            wallSurfacePoint[0],
            wallSurfacePoint[1],
            wallSurfacePoint[2]
          );
          this.__addToAWall(wall, wallEdge);
          break;
        }
      }
    }
    this.__combinedRotation = this.__combineRotations();
  }

  getCorners(xDim, yDim, position) {
    position = position || this.position;

    var halfSize = this.halfSize.clone();

    var c1 = new Vector3(-halfSize.x, 0, -halfSize.z);
    var c2 = new Vector3(halfSize.x, 0, -halfSize.z);
    var c3 = new Vector3(halfSize.x, 0, halfSize.z);
    var c4 = new Vector3(-halfSize.x, 0, halfSize.z);
    var transform = new Matrix4();
    transform.makeRotationY(this.rotation.y); //  + Math.PI/2)
    c1.applyMatrix4(transform);
    c2.applyMatrix4(transform);
    c3.applyMatrix4(transform);
    c4.applyMatrix4(transform);

    c1.add(position);
    c2.add(position);
    c3.add(position);
    c4.add(position);

    var corners = [
      { x: c1.x, y: c1.z },
      { x: c2.x, y: c2.z },
      { x: c3.x, y: c3.z },
      { x: c4.x, y: c4.z },
    ];

    return corners;
  }

  __parametricGeometryUpdate(evt, updateForWall = true) {
    let box = this.__parametricClass.geometry.boundingBox;
    this.__size = box.getSize(new Vector3());
    this.__halfSize = this.__size.clone().multiplyScalar(0.5);
    if (this.__currentWall && updateForWall) {
      let point = Utils.cartesianFromBarycenter(
        this.__currentWallEdge?.vertices,
        this.__barycentricLocation
      );
      this.snapToWall(point, this.__currentWall, this.__currentWallEdge);
    }
  }

  __edgeDeleted(evt) {
    if (this.__currentWall) {
      let wallEdge =
        this.__metadata.wallSide === "front"
          ? this.__currentWall.frontEdge
          : this.__currentWall.backEdge;
      this.__currentWallEdge = null;
      let point = Utils.cartesianFromBarycenter(
        wallEdge?.vertices,
        this.__barycentricLocation
      );
      this.snapToWall(point, this.__currentWall, wallEdge);
    }
  }

  __followWall(evt) {
    console.debug(
      "item.js -> __followWall -> item",
      this.id,
      this.__isWallDependent,
      this.__currentWall.id,
      !this.__offlineUpdate
    );
    if (this.__isWallDependent && this.__currentWall) {
      let point = Utils.cartesianFromBarycenter(
        this.__currentWallEdge?.vertices,
        this.__barycentricLocation
      );
      this.snapToWall(point, this.__currentWall, this.__currentWallEdge);
    }
  }

  __addToAWall(toWall, toWallEdge) {
    console.debug(
      "item.js -> __addToAWall -> __currentWall",
      this.id,
      this.__currentWall,
      toWallEdge.normal
    );
    if (toWall === undefined || !toWall || toWall === "undefined") {
      return;
    }
    if (this.__currentWall && this.__currentWall !== toWall) {
      console.debug(
        "item.js -> __addToAWall -> removing listener",
        this.id,
        this.__currentWall.id
      );
      this.__currentWall.removeEventListener(
        EVENT_MOVED,
        this.__followWallEvent
      );
      this.__currentWallEdge.removeEventListener(
        EVENT_DELETED,
        this.__edgeDeletedEvent
      );
      this.__currentWall.removeItem(this);
    }

    toWallEdge.__normal = new Vector3(
      Math.round(toWallEdge.normal.x),
      Math.round(toWallEdge.normal.y),
      Math.round(toWallEdge.normal.z)
    );
    console.debug(
      "item.js -> __addToAWall -> toWallEdge.__normal",
      this.id,
      toWallEdge.normal
    );
    let barycentricUVW = Utils.barycentricFromCartesian(
      toWallEdge?.vertices,
      this.__currentWallSnapPoint
    );
    this.__currentWall = toWall;
    this.__currentWallEdge = toWallEdge;
    this.__currentWallNormal = this.__currentWallEdge.normal;
    this.__isWallDependent = true;
    this.__barycentricLocation = barycentricUVW.clone();

    if (
      !this.__currentWall.hasEventListener(EVENT_MOVED, this.__followWallEvent)
    ) {
      console.debug(
        "DEBUG: item.js -> __addToAWall -> adding event listener",
        this.id,
        this.__currentWall.id
      );
      this.__currentWall.addEventListener(EVENT_MOVED, this.__followWallEvent);
      this.__currentWallEdge.addEventListener(
        EVENT_DELETED,
        this.__edgeDeletedEvent
      );
    }

    this.__metadata.wall = this.__currentWall.id;
    this.__metadata.wallSide = toWallEdge.front ? "front" : "back";
    this.__metadata.wallSurfacePoint = [
      this.__currentWallSnapPoint.x,
      this.__currentWallSnapPoint.y,
      this.__currentWallSnapPoint.z,
    ];
    this.__offlineUpdate = true; //Really important as it will lead to a lot of recursion
    this.__currentWall.addItem(this); //This causes wall to dispatch event_moved triggering followWall, which will trigger this method again
    this.__offlineUpdate = false; //Really important as it will lead to a lot of recursion

    this.combinedRotation = this.__combineRotations();
  }

  /** */
  __moveToPosition() {}

  __getMetaData() {
    return {
      id: this.id,
      dbid: this.metadata.dbid,
      price: this.metadata.price,
      thumbnail: this.metadata.thumbnail,
      itemName: this.metadata.itemName,
      description: this.metadata.description,
      itemType: this.metadata.itemType,
      modelURL: this.metadata.modelUrl,
      position: this.position.toArray(),
      rotation: this.rotation.toArray(),
      innerRotation: this.innerRotation.toArray(),
      scale: this.scale.toArray(),
      size: this.size.toArray(),
      fixed: this.__fixed,
      resizable: this.__resizable,
      mesh: this.mesh,
      meshmap: this.meshmap,
      // Kitchen backsplash config ({on,height,materialUrl,color}) — kept so it
      // survives an explicit metadata rebuild and reloads with the project.
      backsplash: this.metadata.backsplash,
    };
  }

  __metaDataUpdate(propertyname) {
    this.dispatchEvent({ type: EVENT_UPDATED, property: propertyname });
  }

  __combineRotations() {
    let quatEuler = new Quaternion().setFromEuler(
      new Euler(
        this.innerRotation.x,
        this.innerRotation.y,
        this.innerRotation.z
      )
    );
    let quatRotation = new Quaternion().setFromEuler(
      new Euler(this.rotation.x, this.rotation.y, this.rotation.z)
    );
    let combinedRotation = quatEuler.multiply(quatRotation);
    let finalEuler = new Euler().setFromQuaternion(combinedRotation);
    return new Vector3(finalEuler.x, finalEuler.y, finalEuler.z);
  }

  updateMetadataExplicit() {
    this.__metadata = this.__getMetaData();
  }

  snapToPoint(point, normal, intersectingPlane, toWall, toFloor, toRoof) {
    this.position = point;
  }

  snapToWall(point, wall, wallEdge) {}

  newWallEdge() {
    let wallEdge =
      this.__metadata.wallSide === "front"
        ? this.__currentWall.frontEdge
        : this.__currentWall.backEdge;
    this.__currentWallEdge = null;
    this.__currentWallEdge = wallEdge;
  }

  dispose() {
    console.debug("item.js -> dispose", this.id);
    if (this.isParametric && this.__parametricClass) {
      this.__parametricClass.removeEventListener(
        EVENT_PARAMETRIC_GEOMETRY_UPATED,
        this.__parametricGeometryUpdateEvent
      );
    }
    if (this.__currentWall) {
      this.__currentWall.removeEventListener(
        EVENT_MOVED,
        this.__followWallEvent
      );
      this.__currentWall.removeItem(this);
    }
    if (this.__currentWallEdge) {
      this.__currentWallEdge.removeEventListener(
        EVENT_DELETED,
        this.__edgeDeletedEvent
      );
    }
  }

  get id() {
    return this.__id;
  }

  get metadata() {
    if (this.isParametric) {
      this.__metadata.subParametricData = this.__parametricClass.metadata;
    }
    return this.__metadata;
  }

  set metadata(mdata) {
    this.__metadata = mdata;
    this.__applyMetaData();
  }

  get position2d() {
    return this.__position2d;
  }

  get position() {
    return this.__position;
  }
  set position(p) {
    this.__position2d.x = p.x;
    this.__position2d.y = p.z;
    /*if (this.__metadata.itemType === MODEL_TYPES.IN_WALL_FLOOR_UNIT) {
      p = new Vector3(p.x, 0, p.z + 3);
    }*/
    this.__position.copy(p);
    this.__metadata.position = this.__position.toArray();
    this.__moveToPosition();
    this.__metaDataUpdate("position");
  }

  get rotation() {
    return this.__rotation;
  }

  set rotation(r) {
    let old = this.__rotation.clone();
    let current = r.clone();
    if (old.sub(current).length() < 1e-4) {
      return;
    }
    this.__rotation.copy(r);
    this.__metadata.rotation = this.__rotation.toArray();
    this.__metaDataUpdate("rotation");
    this.combinedRotation = this.__combineRotations();
  }

  get innerRotation() {
    return this.__innerRotation;
  }

  set innerRotation(eulerRotation) {
    this.__innerRotation = eulerRotation.clone();
    this.__metadata.innerRotation = this.__innerRotation.toArray();
    this.__metaDataUpdate("innerRotation");
    this.combinedRotation = this.__combineRotations();
  }

  get combinedRotation() {
    return this.__combinedRotation;
  }

  set combinedRotation(rotation) {
    this.__combinedRotation = rotation;
    this.__metaDataUpdate("combinedRotation");
  }

  get scale() {
    return this.__scale;
  }

  set scale(s) {
    this.__scale.copy(s);
    this.__metadata.scale = this.__scale.toArray();
    this.__metaDataUpdate("scale");
  }
  /**
   * This is a read-only property. This can be changed only internally with private and protected acces
   */
  get size() {
    return this.__size.clone();
  }

  get mesh() {
    return this.__mesh;
  }

  set mesh(value) {
    this.__mesh.copy(value);
    this.__metadata.mesh = this.__mesh;
    this.__metaDataUpdate("mesh");
  }

  get meshmap() {
    return this.__meshmap;
  }

  set meshmap(value) {
    this.__meshmap = value;
    this.__metadata.meshmap = this.__meshmap;
    this.__metaDataUpdate("meshmap");
  }

  get modelURL() {
    return this.__metadata.modelURL;
  }

  set modelURL(value) {
    this.__metadata.modelURL = value;
    this.__metaDataUpdate("modelURL");
  }

  get fixed() {
    return this.__fixed;
  }

  set fixed(flag) {
    this.__fixed = flag;
    this.__metaDataUpdate("fixed");
  }

  get frontVisible() {
    return this.__frontVisible;
  }

  set frontVisible(flag) {
    this.__frontVisible = flag;
  }

  get backVisible() {
    return this.__backVisible;
  }

  set backVisible(flag) {
    this.__backVisible = flag;
  }

  get visible() {
    return this.__visible;
  }

  set visible(flag) {
    this.__visible = flag;
    // this.frontVisible = false;
    // this.backVisible = false;
    this.__metaDataUpdate("visible");
  }

  get isParametric() {
    return this.__isParametric;
  }

  get baseParametricType() {
    return this.__baseParametricType;
  }

  get subParametricData() {
    return this.__subParametricData;
  }

  get parametricClass() {
    return this.__parametricClass;
  }

  get resizable() {
    return this.__resizable;
  }

  get itemName() {
    return this.__metadata.itemName;
  }

  get itemType() {
    return this.__metadata.itemType;
  }

  get halfSize() {
    return this.__halfSize.clone();
  }

  get intersectionPlanes() {
    return this.__customIntersectionPlanes;
  }

  get isWallDependent() {
    return this.__isWallDependent;
  }

  get isBoundToFloor() {
    return this.__boundToFloor;
  }

  get offlineUpdate() {
    return this.__offlineUpdate;
  }

  get wallSide() {
    return this.__metadata.wallSide;
  }
}
